// src/components/layout/app-header.tsx

"use client";

import React from "react";
import { Bell, Search, Wallet } from "lucide-react";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

export function AppHeader({ unreadCount, onTabChange, onNavigateToWallet }: any) {
  return (
    <header className="h-16 border-b border-white/5 bg-slate-900/40 backdrop-blur-md flex items-center justify-between px-6 z-20 flex-row-reverse shrink-0">
      <div className="flex items-center gap-4 flex-row-reverse">
        <SidebarTrigger className="md:hidden" />
        <div className="relative hidden md:block">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input placeholder="البحث في نكسوس..." className="w-64 pr-9 h-9 bg-white/5 border-white/10 rounded-lg text-sm text-right" />
        </div>
      </div>
      <div className="flex items-center gap-4 flex-row-reverse">
        <Button variant="ghost" size="icon" className="text-muted-foreground relative" onClick={() => onTabChange("notifications")}>
          <Bell className="size-5" />
          {unreadCount > 0 && <Badge className="absolute top-2 left-2 h-4 w-4 p-0 flex items-center justify-center bg-red-500 border border-slate-900 text-[9px]">{unreadCount}</Badge>}
        </Button>
        <div className="h-8 w-px bg-white/10" />
        <Button variant="outline" className="h-9 px-4 rounded-xl border-white/10 gap-2 text-xs font-bold text-white hover:bg-white/5 flex-row-reverse" onClick={onNavigateToWallet}>
          <Wallet className="size-4 text-primary" /> رصيد المحفظة
        </Button>
      </div>
    </header>
  );
}

// Super-Angular/src/app/layout/header/app-header.component.ts
import { Component, inject } from '@angular/core';
import { SidebarService } from '../../core/sidebar.service';
import { LucideAngularModule, Search, Bell, Wallet, ChevronUp } from 'lucide-angular';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [LucideAngularModule],
  templateUrl: './app-header.component.html',
  styleUrls: ['./app-header.component.scss']
})
export class AppHeaderComponent {
  sidebarService = inject(SidebarService);

  // Icons
  SearchIcon = Search;
  BellIcon = Bell;
  WalletIcon = Wallet;
  ChevronUpIcon = ChevronUp;

  unreadCount = 0; // Will be connected to a notification service later

  toggleHeader() {
    this.sidebarService.toggleHeader();
  }

  navigateToWallet() {
    // Router logic will go here
  }
}

<header class="app-header">
  <div class="left-section">
    <!-- Search Bar -->
    <div class="search-container">
      <div class="search-icon-wrapper">
        <lucide-icon [img]="SearchIcon" size="16" class="text-muted"></lucide-icon>
      </div>
      <input type="text" placeholder="البحث في نكسوس..." class="search-input" />
    </div>
  </div>

  <div class="right-section">
    <!-- Toggle Header Button -->
    <button class="icon-button" (click)="toggleHeader()">
      <lucide-icon [img]="ChevronUpIcon" size="20"></lucide-icon>
    </button>
    
    <div class="divider"></div>
    
    <!-- Notifications -->
    <button class="icon-button relative-badge">
      <lucide-icon [img]="BellIcon" size="20"></lucide-icon>
      @if (unreadCount > 0) {
        <span class="badge">{{ unreadCount }}</span>
      }
    </button>
    
    <div class="divider-large"></div>
    
    <!-- Wallet -->
    <button class="wallet-button" (click)="navigateToWallet()">
      <lucide-icon [img]="WalletIcon" size="16" class="text-primary"></lucide-icon>
      رصيد المحفظة
    </button>
  </div>
</header>
